import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { GetStaticProps } from 'next'
import { fetchAllAccounts, AccountInfo } from './api/accounts'
import Account from '../components/account'
import Statuses from '../components/statuses'
import AccountList from '../components/account_list'


export const getStaticProps: GetStaticProps = async (context) => {
  const accounts = await fetchAllAccounts()
  if(accounts) {
    return {
      props: {
        accounts
      }
    }
  }

  return {
    notFound: true
  }
}

export default function Home({ accounts }: { accounts: AccountInfo[] }) {

  function Accounts() {
    return accounts.map(account => (
      <Account account={account} />
    ))
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Mastodon Accounts</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className={styles.title}>Mastodon Accounts</h1>
      <Statuses accounts={accounts} />
      <AccountList accounts={accounts} />

    </div>
  )
}
